### ISSUE TITLE
tdp calc

### ISSUE THREAD

**Issue by xtremenerdrage** [matoom/calculators#1]
Any chance the online TDP calculator could get looked at?

**Comment by matoom** [comment]
I'm not sure if i understand but has there been any new developments in regards to tdps? Everything seems to check out as far as i know.

**Comment by xtremenerdrage** [comment]
I was totally pasting skills in not stats, at high levels there are some
small incongruences but it's like 99% accurate so gives a good idea. You
can close this request its not valid.

Thank you

**Comment by matoom** [comment]
Okay, that explains it and you're right there are some known issues with rounding the calculations with javascript vs ingame but honestly i just don't know how to fix that.
